### ISSUE TITLE
starting with bluegiga 

### ISSUE THREAD

**Issue by abdessattar** [jrowberg/bluegiga#1]
Hello everyone
I have a project with Bluegiga kit, I saw a video on youtube tells me that you must have the following message "DKBLE112 ..." at the first connection of the card with the computer. But in my case I could not see this message.
so I need someone can help me with my problem.
Thank you in advance.
Best regards .

**Comment by jrowberg** [comment]
Hello @abdessattar,

Whether text is displayed on the devkit's LCD depends on what firmware is running on the kit. The factory default firmware for devkits will display this if the LCD is enabled via the hardware peripheral switch on the kit, but otherwise (different firmware or LCD off) it will not be seen. You might have non-default firmware on the kit.

However, this is not the best place to request this kind of support; this is a Github repository where issues reported should specifically concern items hosted on the repository. This type of question would be more better suited to the Silicon Labs community forum:

http://community.silabs.com/t5/Wireless/bd-p/4

**Comment by abdessattar** [comment]
thank you very match  @jrowberg
